// sidebars.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Connection & Auth',
      items: [{ type: 'autogenerated', dirName: 'connection' }],
    },
    {
      type: 'category',
      label: 'Protocol System',
      items: [{ type: 'autogenerated', dirName: 'protocol' }],
    },
    {
      type: 'category',
      label: 'Codec System',
      items: [{ type: 'autogenerated', dirName: 'codec' }],
    },
    {
      type: 'category',
      label: 'Plugin System',
      items: [{ type: 'autogenerated', dirName: 'plugin-system' }],
    },
    {
      type: 'category',
      label: 'Packet Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'packets'
        }
      ],
    },
  ],
};

module.exports = sidebars;